scan_for_calendars:
  name: Scan for new calendars
  description: "Scan for newly available calendars"

scan_for_todo_lists:
  name: Scan for new todo lists
  description: "Scan for newly available todo lists"

respond_calendar_event:
  name: Respond to an event
  description: "Respond to calendar event/invite"
  target:
    device:
      integration: o365
    entity:
      integration: o365
      domain: calendar
  fields:
    event_id:
      name: Event ID
      description: ID for event, can be found as an attribute on your calendar entity's events
      example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      required: true
      selector:
        text:
    response:
      name: Response
      description: "The response to the invite [Accept, Tentative, Decline]"
      example: Decline
      required: true
      selector:
        text:
    message:
      name: Message
      description: "The response message to the invite (Optional)"
      example: "I cannot attend this meeting"
      selector:
        text:
    send_response:
      name: Send Response
      description: "Send the response to the organizer (Optional)"
      example: True
      selector:
        boolean:

create_calendar_event:
  name: Create a new event
  description: Create new calendar event
  target:
    device:
      integration: o365
    entity:
      integration: o365
      domain: calendar
  fields:
    subject:
      name: Subject
      description: The subject of the created event
      example: Clean up the garage
      required: true
      selector:
        text:
    start:
      name: Start
      description: The start time of the event
      example: "2025-03-22 20:00:00"
      required: true
      selector:
        datetime:
    end:
      name: End
      description: The end time of the event
      example: "2025-03-22 20:30:00"
      required: true
      selector:
        datetime:
    body:
      name: Body
      description: The body text for the event (optional)
      example: Remember to also clean out the gutters
      selector:
        text:
    location:
      name: Location
      description: The location for the event (optional)
      example: "1600 Pennsylvania Ave Nw, Washington, DC 20500"
      selector:
        text:
    categories:
      name: Categories
      description: list of categories for the event (optional)
      selector:
        text:
    sensitivity:
      name: Sensitivity
      description: "The sensitivity for the event (optional) [Normal, Personal, Private, Confidential]"
      example: normal
      selector:
        select:
          mode: dropdown
          options:
            - label: "Normal"
              value: "normal"
            - label: "Personal"
              value: "personal"
            - label: "Private"
              value: "private"
            - label: "Confidential"
              value: "confidential"
    show_as:
      name: Show As
      description: "Show event as (optional) [Free, Tentative, Busy, Oof, WorkingElsewhere, Unknown]"
      example: busy
      selector:
        select:
          mode: dropdown
          options:
            - label: "Free"
              value: "free"
            - label: "Tentative"
              value: "tentative"
            - label: "Busy"
              value: "busy"
            - label: "Out of Office"
              value: "oof"
            - label: "Working Elsewhere"
              value: "workingElsewhere"
            - label: "Unknown"
              value: "unknown"
    is_all_day:
      name: All Day
      description: Set whether event is all day (optional)
      example: False
      selector:
        boolean:
    attendees:
      name: Attendees
      description: "list of attendees formatted as email: example@example.com type: Required, Optional, or Resource (optional)"
      selector:
        object:

modify_calendar_event:
  name: Modify an event
  description: Modify existing calendar event, all properties except event_id are optional.
  target:
    device:
      integration: o365
    entity:
      integration: o365
      domain: calendar
  fields:
    event_id:
      name: Event ID
      description: ID for the event, can be found as an attribute on you calendar entity's events
      example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      required: true
      selector:
        text:
    subject:
      name: Subject
      description: The subject of the created event
      example: Clean up the garage
      selector:
        text:
    start:
      name: Start
      description: The start time of the event
      example: "2025-03-22 20:00:00"
      selector:
        datetime:
    end:
      name: End
      description: The end time of the event
      example: "2025-03-22 20:30:00"
      selector:
        datetime:
    body:
      name: Body
      description: The body text for the event
      example: Remember to also clean out the gutters
      selector:
        text:
    location:
      name: Location
      description: The location for the event
      example: "1600 Pennsylvania Ave Nw, Washington, DC 20500"
      selector:
        text:
    categories:
      name: Categories
      description: list of categories for the event
      selector:
        text:
    sensitivity:
      name: Sensitivity
      description: "The sensitivity for the event[Normal, Personal, Private, Confidential]"
      example: normal
      selector:
        select:
          mode: dropdown
          options:
            - label: "Normal"
              value: "normal"
            - label: "Personal"
              value: "personal"
            - label: "Private"
              value: "private"
            - label: "Confidential"
              value: "confidential"
    show_as:
      name: Show As
      description: "Show event as [Free, Tentative, Busy, Oof, WorkingElsewhere, Unknown]"
      example: busy
      selector:
        select:
          mode: dropdown
          options:
            - label: "Free"
              value: "free"
            - label: "Tentative"
              value: "tentative"
            - label: "Busy"
              value: "busy"
            - label: "Out of Office"
              value: "oof"
            - label: "Working Elsewhere"
              value: "workingElsewhere"
            - label: "Unknown"
              value: "unknown"
    is_all_day:
      name: All Day
      description: Set whether event is all day
      example: False
      selector:
        boolean:
    attendees:
      name: Attendees
      description: "list of attendees formatted as email: example@example.com type: Required, Optional, or Resource"
      selector:
        object:

remove_calendar_event:
  name: Delete an event
  description: Delete calendar event
  target:
    device:
      integration: o365
    entity:
      integration: o365
      domain: calendar
  fields:
    event_id:
      name: Event ID
      description: ID for the event, can be found as an attribute on you calendar entity's events
      example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      required: true
      selector:
        text:

