services:
  ha-calendar-sync:
    build: .
    container_name: ha-to-o365-sync
    command: ["python", "sync.py", "--continuous"]
    volumes:
      # Bind mount for configuration
      - ./config.yaml:/app/config.yaml:ro
      # Bind mount for tokens (must authenticate locally first)
      - ./.tokens:/app/.tokens
    restart: unless-stopped
    environment:
      - TZ=UTC
      - SYNC_INTERVAL=900 # 15 minutes between syncs
      - MAX_RETRIES=3 # Max retries on failure before backing off
      - BACKOFF_TIME=3600 # 1 hour backoff on repeated failures
      - LOG_LEVEL=info